language: node_js
node_js:
  - "--lts"

env:
  global:
    - CODECOV_TOKEN=c38634d0-bb81-4363-9edb-46dea0dea35f

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - npm install
  - npm install -g codecov
  - npm install -g snyk

script:
  - istanbul cover ./node_modules/mocha/bin/_mocha test/*.js --reporter lcovonly -- -R spec
  - codecov
  - snyk auth $SNYK_TOKEN
  - snyk test

after_success:
  - snyk monitor